name: verify

on:
  push:
    branches-ignore:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Maven setup
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "magnolia.enterprise.group",
              "username": "${{secrets.MGNL_NEXUS_USER}}",
              "password": "${{secrets.MGNL_NEXUS_PASS}}"
            }]
      - name: Test
        run: mvn dependency:get -Dartifact=info.magnolia:magnolia-license:2.0.0
      - name: Maven verify
        run: mvn verify --batch-mode